### PR TITLE
fix localStorage in IE8

### LINKED ISSUE #793: Stopped working on IE8

### PR DESCRIPTION
**Pull request by thgreasi**
Resolves #793

### CODE REVIEW

**Comment by thgreasi** [comment]
I will try to cut a new v1.5 release later today if you don't have time for it.

**Comment by tofumatt** [comment]
Actually I have some time this morning in like thirty minutes so I can handle it :-)

**Comment by thgreasi** [comment]
Oh sorry, just released! How about a re-review on drop instance PR?

**Comment by tofumatt** [comment]
Oh, no worries!

Sure thing, I’ll get to that today :-)

**Pull request merged**
