### PR TITLE
Upgrade lie to 3.1.1

### PR DESCRIPTION
**Pull request by cherewaty**
Upgrades `lie`'s `es3ify` dependency, for far fewer dependencies on the deprecated `esprima-fb`.

### CODE REVIEW

**Comment by thgreasi** [comment]
A welcomed near the end of the year PR definitely that's good to merge 👍 

Some parts in the PR description confused me / left me with questions though.
I didn't get the `esprima-fb` part.
Also I'm not sure whether updated lie dependency affects us, since we are just pointing to lie's polyfill file directly instead of the source or building it yourself.

**Comment by cherewaty** [comment]
A little more context about the problem I'm trying to solve, that led me to this PR:

I have an app that relies on both `localforage` and `recast`.

The version of `es3ify` requested by the version of `lie`'s `package.json` requested by `localforage` includes a dependency on `esprima-fb@~3001.0001.0000-dev-harmony-fb`.

`recast` includes a dependency on `esprima-fb@~3001.1.0-dev-harmony-fb`.

When running `yarn install`, Yarn throws a warning that those two versions of `esprima-fb` are "trying to unpack in the same destination," because the decimals reduce to the same thing. Yarn says "This could result in a non deterministic behavior, skipping."

Upgrading `lie` should fix that warning, since the zero-padded version string will be gone.

**Comment by rodrigues** [comment]
came to this repo to find out more about the issue, nice to see there's a fix on the way, thanks @cherewaty 👏🏼

just bringing a bit more info on it: when `yarn check` runs, two issues are related:

```
warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same 
destination "…/Library/Caches/Yarn/v1/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in a non deterministic behavior, skipping.
```

```
error "esprima-fb" is wrong version: expected "3001.1.0-dev-harmony-fb", got null
```

I always see the warning when running `yarn install` also

**Comment by thgreasi** [comment]
Status: Just want to confirm that it still works in IE8 (which it should) and will merge and release as v1.6 during the weekend.

**Comment by giuseppeg** [comment]
@thgreasi / @cherewaty / @tofumatt Would it be possible to release a patch version? The package is not usable with yarn because of this issue.

**Comment by tofumatt** [comment]
Sure thing. I’ll get to it today!

- Matt (Sent from mobile)

**Comment by tofumatt** [comment]
FYI 1.5.6 has been released, please let me know if that fixes your issue!

**Comment by giuseppeg** [comment]
@tofumatt works like a charm, thank you!

**Comment by thgreasi** [comment]
@tofumatt Thanks, you are so cool that you remembered that master is v1.6.0-pre.
I'm feeling bad of this, but I think that I will have 2 PRs for you during the weekend for v1.6 :)

**Pull request merged**
