### PR TITLE
docs: Add link to Chinese documentation (fix #796)

### LINKED ISSUE #796: API docs translation site in Chinese
hi, I've translated the doc page into Chinese as blow:

[localForage in Chinese](https://localforage.docschina.org)

so, I'd like to add the link of Chinese site on the official page, could I?

### PR DESCRIPTION
**Pull request by tofumatt**
Hi @xmoyKing, does this look okay? Sorry, I just used Google Translate for the text. If I can make it better please tell me 😄

### CODE REVIEW

**Comment by xmoyKing** [comment]
It's really great! Don't worry, your translation is correct. :) 👍

**Comment by tofumatt** [comment]
Awesome, thank you again! 😄

I noticed the logo for localForage is not on the main page of http://docschina.org by the way; if there is a way to add it please let me know :-)

**Comment by xmoyKing** [comment]
Is this the logo of localForage?

screenshot blow:
screenshot

If so, I will add this  picture being the logo and icon of localForage on main page.

**Comment by thgreasi** [comment]
I was working on a logo for some time but we never had a discussion about it. There is a repo under the localforage org and the org itself uses it.
See: https://github.com/localForage/localForage-logo

**Comment by xmoyKing** [comment]
@thgreasi I see, thx, 

I am using [the basic version logo for localForage](https://htmlpreview.github.io/?https://github.com/localForage/localForage-logo/blob/master/logo.html)  on the main page of docschian.org

**Comment by tsekityam** [comment]
@xmoyKing https://localforage.docschina.org is down, could you please check?

**Comment by xmoyKing** [comment]
> @xmoyKing https://localforage.docschina.org is down, could you please check?

sorry, reply so late. and this link is normally accessable now.

**Pull request merged**
