### PR TITLE
Return config set driver promise

### LINKED ISSUE #634: Possibly unhandled promise in .config()
@tofumatt now that I started looking for unhandled promises, I just came by [this one in `config()`](https://github.com/localForage/localForage/blob/4fe872cf0f866cb5bcc54848ecbdfb44915bfd08/src/localforage.js#L153).
What do you think we should do? Should we:
* silence it with a `catch()` like we did with the constructor
* return that promise if a `driver` is passed (which is still truthy, so it's probably not breaking)
* other thing that I couldn't think of since its early in the morning

### PR DESCRIPTION
**Pull request by thgreasi**
Resolves #634

### CODE REVIEW

**Comment by thgreasi** [comment]
@tofumatt Please review and merge. It's more or less what we talked about in #634 .

**Comment by tofumatt** [comment]
I guess this fixes up a lot of our promise things, should we release 1.5 now to solve them for folks?

**Comment by thgreasi** [comment]
How about also doing #632 first? I should also give a note to the Ionic folks since they might need to resolve some conflicts, now that we include typings.

**Comment by thgreasi** [comment]
@tofumatt we can cut a release. Should we schedule it on 22 Dec, so that we can give a notice (and some time) to the Ionic guys (as per #615)?

**Comment by tofumatt** [comment]
Sounds good, or at this point either the 23 or whenever works for them!

I'll be around and can make one, not too many holiday plans 😄

**Pull request merged**
