### PR TITLE
Use Object.prototype.toString for type checks

### PR DESCRIPTION
**Pull request by duzun**
Consider the following code using 'LOCALSTORAGE' driver:

```js
localforage.setItem('test', '[object Blob]')
.then(() => {
    localforage.getItem('test');
});
```

This is 100% legitim use case. But it fails because the way serialize() checks value's type.

Basically instead of `value.toString()` it should be `Object.prototype.toString.call(value)`, which yields `"[object String]"` instead of `"[object Blob]"` for the above example.

Another potential issue is `value instanceof Blob`. 
I see two scenarios where it would get wrong:

1. `Blob` type doesn't exist (blob not supported);
2. `value` comes from a different window context (eg. an iframe).

### CODE REVIEW

**Comment by tofumatt** [comment]
Hi there!

This looks good but sadly it has merge conflicts with `master`. Could you rebase your changes against master and push again? Thanks!

**Comment by duzun** [comment]
No problem!

**Comment by duzun** [comment]
Done!

**Comment by tofumatt** [comment]
You rock, thanks very much!

**Comment by duzun** [comment]
You are welcome!

**Pull request merged**
