### PR TITLE
Batch writes

### PR DESCRIPTION
**Pull request by michielbdejong**
Continuation of #320

### CODE REVIEW

**Comment by michielbdejong** [comment]
The tests are passing for the wrong reason now (some tests stay 'pending')

**Comment by michielbdejong** [comment]
@tofumatt how would you like me to implement the switch? For now I've done it [this way](https://github.com/localForage/localForage/pull/656/commits/53d23db338a58ae2fb3b03b94ffb74d5ce2e8242). Another option would be to make "indexeddb with auto-batching" a separate driver type?

**Comment by michielbdejong** [comment]
This worries me:

https://travis-ci.org/localForage/localForage/builds/197660273#L542

It would suggest that all tests for the indexeddb driver are currently being skipped on Travis. :/ Should they be executed on SauceLabs somehow?

**Comment by michielbdejong** [comment]
setItem gets wrapped in localforage.ready() which means even if localforage is already ready, `setItem(foo, bar)` effectively becomes `Promise.resolve().then(() => setItem(foo, bar))`. That's a pity because best performance when setItem is used in a loop, it would have been good if setItem queues its task synchronously. I had a unit test for that, but i'll disable it.

**Comment by michielbdejong** [comment]
Tests still being skipped in  test/test.api.js and test/test.webpack.html.

**Comment by michielbdejong** [comment]
Fixed the tests that were failing by removing the call to `self.ready()` from withing `updateDatabase`

**Comment by tofumatt** [comment]
Wow, thanks for keeping on this. I know it's been ages but I still do have my eye on it 😓

**Comment by michielbdejong** [comment]
Speedup in Firefox on my laptop: *4x*

screenshot from 2018-06-29 16-04-22

Speedup in Chrome on my laptop: *34x*

screenshot from 2018-06-29 16-08-52

**Comment by michielbdejong** [comment]
Yes, it has been the bottom item on my list of open PRs for years, finally found some time to fix those failing tests! :)

**Comment by michielbdejong** [comment]
Is someone available to review this?

**Comment by tofumatt** [comment]
Sorry, yes, I really meant to but have been really distracted with other work, kitchen remodelling, etc.

**Comment by tofumatt** [comment]
My hope is I'll have a look Friday, this weekend, or Monday at the latest. Sorry! 😓

**Comment by ayrtonvwf** [comment]
Hey @tofumatt, any progress in this pull request? I don't wanna put any pressure, I just have to decide whether to use localForage in my production APP or not and it depends on this pull request. I'd be happy to help with anything cause I really wanna use localForage, but I don't know how to help.

**Comment by tofumatt** [comment]
I'm really sorry but I have been renovating my kitchen in my spare time for the past month or so and it's meant really limited time for other projects. I meant to get to this earlier and I know I'm quite behind on it. 😢

It's a busy time with work at the day job too (we are close to shipping the new WordPress editor and are spending a lot of time fixing bugs).

I'll try my best to prioritise this next time I have a few hours to spend on localForage, it's just been a really busy time and most of my efforts have been on my kitchen, as I miss eating things that aren't soup and grocery store sandwiches 😉

**Comment by graememcc** [comment]
Drive-by comment: I pulled in @michielbdejong's fork with this branch to see if it helped with a perf issue we were hitting at the day job. That codebase uses the `createInstance` API to create various data-stores.

If we set the auto-batching flag after creating an instance, it was reset when we performed an operation on the store: at some point during the operation (I think the `ready` check) we end up in https://github.com/localForage/localForage/blob/eb40c0d7b56d66cd80df083f09513e5a9fa286c5/src/localforage.js#L330, which seems to be doing the equivalent of `Object.assign()`, and clobbers the `useAutoBatching` flag value with the one from https://github.com/localForage/localForage/blob/eb40c0d7b56d66cd80df083f09513e5a9fa286c5/src/drivers/indexeddb.js#L1158.

(Of course, we might have been misusing `localForage`).

**Comment by michielbdejong** [comment]
Thanks for reporting! It looks like the tests set autobatching on the global `window.localforage` object in https://github.com/localForage/localForage/pull/656/files#diff-447b2c1caef3d852887ac29e6e62df10R24 and then use `window.localforage.setDriver`.

**Comment by mikeyyyzhao** [comment]
I tried setting the autoBatchFlag to true (localforage.useAutoBatching = true) but when I ran setItem on our array of key-value pairs, it still took over a minute to set 15,000 rows of data. Is that normal? My code is below:

`  setItInIndexDB(events) {
    Promise.all(
      events.map(e => {
        return localForage.setItem(e.user_event_id, e);
      })
    ).then(function(results) {
        console.log('finished setting events', results);
    });
  }`

**Comment by tofumatt** [comment]
@mikeyyyzhao Are you using the main `master` branch (eg installed from NPM) or are you trying this branch?

Are the events items you're storing especially large/complex? Can you performance test the writes to see if it's slower as time goes on (this can happen with IndexedDB in my experience as the database gets a _lot_ larger.)

**Comment by Juice10** [comment]
Hoi @michielbdejong I noticed that this PR was closed. Do you remember why? Was the underlying issue solved?

**Comment by michielbdejong** [comment]
@Juice10 no, I just closed it as stale. You're free to checkout the branch and try if it works for you, and/or build on top of the code from this PR.

**Pull request closed without merging**
