### PR TITLE
Updated deps

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by nolanlawson** [comment]
+1 when green.

Also long term we may want to use Greenkeeper: https://greenkeeper.io/

**Comment by tofumatt** [comment]
Looks like these tests don't pass because of an `npm install` error. Could that be fixed up please? 😄

**Comment by amilajack** [comment]
Not sure why this is happening. It install on my machine perfectly.

**Comment by amilajack** [comment]
@tofumatt also what do you think about migrating to eslint?

**Comment by tofumatt** [comment]
Totally 👍🏻 — see #559 😀

**Comment by amilajack** [comment]
@nolanlawson good idea! I've been using [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) all this time:

```bash
ncu -au
npm update
```

**Comment by amilajack** [comment]
@tofumatt also what do you think about migrating a few grunt tasks to npm scripts? This can get rid of a lot of boilerplate and remove dependencies.

**Comment by tofumatt** [comment]
I’m for that too! I’ve done some of that in my karma branch, but it’s not
ready yet, so if you add it separately I’m fine with that.

**Comment by tofumatt** [comment]
This has definitely bitrotted but know it's on our radar, hopefully for V2 but if not for V3. I'm aiming to do a lot of cleanup in the repo soon 😃

**Pull request closed without merging**
