### PR TITLE
setItems in bulk in localStorage

### PR DESCRIPTION
**Pull request by himanshu199728**
#952, #953

### CODE REVIEW

**Comment by himanshu199728** [comment]
I'm not getting this why the build failed.

**Comment by thgreasi** [comment]
Repeating what I mentioned in #952
> Hi,
Have you checked https://github.com/localForage/localForage-setItems ?
It sounds like it does exactly what you need for all supported drivers.
We decided to not make this part of the core localforage api, at least initially, since there was also a different approach in the works at that point.

Should we close this?

**Comment by himanshu199728** [comment]
> Repeating what I mentioned in #952
> 
> > Hi,
> > Have you checked https://github.com/localForage/localForage-setItems ?
> > It sounds like it does exactly what you need for all supported drivers.
> > We decided to not make this part of the core localforage api, at least initially, since there was also a different approach in the works at that point.
> 
> Should we close this?

Ok. I have closed the pull request regarding this. Will start working on some other issue.

**Comment by thgreasi** [comment]
Cool, thanks :+1:

**Comment by himanshu199728** [comment]
Actually in code I was trying to have setItems api for localStorage driver and if user try to call setItems() for other drivers then he will get "unsupported service" response in Promise as return.

**Comment by thgreasi** [comment]
Indeed, but localforage-setitems also works for IDB & Websql, as well as any possible custom driver used (like localforage-cordova-sqlite-driver). Are you suggesting something different?

**Comment by himanshu199728** [comment]
I'm saying in context of version of this library setItems() will be available for localStorage but later it will be available for other drivers also. We will have setItems() available for all supported driver but excluding localStorage driver all will return new Promise((resolve, rejext)=>{resolve("Service not available")}). Like if in some authentication service we only having user-password authentication available and if the developer tries to make it for OTP(whose development is not done) it will return "Service not available" as a response.

**Pull request closed without merging**
