### PR TITLE
docs: use cdn for localforage & jquery

### LINKED ISSUE #737: Security vulnerability reported by 'retire'
I have been testing out my project for security vulnerabilities using the NPM module "retire" (https://www.npmjs.com/package/retire). `NeDB` is one of the NPM modules that I use which has `local-forage` as its dependency. Below is the security vulnerability reported by retire:

```
node_modules/nedb/node_modules/localforage/docs/scripts/jquery.min.js
↳ jquery 1.9.1 has known vulnerabilities: severity: medium; issue: 2432, summary: 3rd party CORS request may execute; jquery/jquery#2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
```

I have also reported this in the NeDB issues here: https://github.com/louischatriot/nedb/issues/526

### LINKED ISSUE #746: Include localforage in the GH pages so that visitors can experiment with it
Many popular libraries do that, we should do it as well :)

### PR DESCRIPTION
**Pull request by thgreasi**
Resolves #737
Resolves #746

### CODE REVIEW

**Comment by thgreasi** [comment]
@tofumatt Any hints on how to publish the docs?
I got:
> Warning: Task "copy" not found. 

and after installing `grunt-contrib-copy` I'm getting:
> Warning: Task "build-rules-html" not found.

What do I need to install? Would it make sense to add them to devDependencies as well?

Also what's the process for cutting new releases? Is pushing a tag all that's needed to reach npm with travis autopublish? Is that something that I can help with?

**Comment by tofumatt** [comment]
I thought the docs automatically published themselves these days using gh-pages. Maybe that's broken–do you not see the newest docs after the build on master completes?

For a new release, yeah: all you need do is push a new tag (or cut a new release on GitHub's "Releases" page as it also creates a git tag). Just make sure package.json/etc. is bumped to the same tag before or the `npm publish` step will fail. But yes the tag should be pushed to npm automatically. 😄

**Comment by thgreasi** [comment]
It seems the docs were not up to date, even when comparing with change that were a bit older.
Changed the GH Pages settings to serve the `docs` folder instead of the `gh-pages` branch and now it should be as easy as merging. Perhaps we missed that when migrating to the repo under the `localForage` org.

I will try to release the current master as v1.5.1 during this week or the next weekend if that's ok with you.

**Comment by tofumatt** [comment]
Sounds good to me! Release away! :-)

**Pull request merged**
