### PR TITLE
Added module to package.json for esm suport

### PR DESCRIPTION
**Pull request by quentincaffeino**
Closes: #940

### CODE REVIEW

**Comment by tofumatt** [comment]
Thanks so much! Sorry I didn't get to this yesterday, but I'm shipping a new version now! 😄

**Comment by klarstrup** [comment]
This is probably going to break IE11 etc. that don't support all the newness used in `src/localforage.js`

**Comment by quentincaffeino** [comment]
How is this able to break anything? Just use precompiled option as you've used before. This is just an option for newer modular bundles that support esm.
Correct me if I'm wrong.

**Comment by klarstrup** [comment]
Webpack(and probably rollup) always uses `module` if provided, and most consumers are not set up to transpile code from node_modules so it gets included in it's raw modern form.

**Comment by quentincaffeino** [comment]
True. Can't say anything about webpack, but from what I've found rollup resolves by default to module, and uses main as a fallback ([Docs](https://github.com/rollup/plugins/tree/master/packages/node-resolve#mainfields), [Code](https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/util.js#L31...L45)).

**Comment by tofumatt** [comment]
Yup, this seems to have broke people's builds. I'm reverting it now, sorry.

**Comment by rozek** [comment]
since localForage does not seem to become available as an ECMAScript module in the near future, [I just copied the source code and bundled it myself into an ESM](https://github.com/rozek/localforage-esm) - now I can import with ease, even directly from within a browser (i.e., without requiring a build environment)

**Pull request merged**
